apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    name: proxy3
  name: proxy3
spec:
  replicas: 1
  selector:
    name: proxy3
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: proxy3
        app: cluster
    spec:
      containers:
#      - image: caicloud/harbor_proxy:latest
      - image: registry.dataos.io/liuliu/harbor_proxy:latest 
        imagePullPolicy: Always
        name: proxy3
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/nginx
          name: nginx-config
      dnsPolicy: ClusterFirst
      nodeSelector:
        node: node-3.11
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nginx-config
        secret:
          secretName: nginx-config3
status:
  replicas: 0
