apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    name: ui
  name: ui
spec:
  replicas: 1
  selector:
    name: ui
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: ui
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USR
          value: root
        - name: REGISTRY_URL
          value: http://registry:5000
        - name: CONFIG_PATH
          value: /etc/ui/app.conf
        - name: HARBOR_REG_URL
          value: localhost
        - name: HARBOR_ADMIN_PASSWORD
          value: 99B0-6599E123D24E
        - name: HARBOR_URL
          value: http://localhost
        - name: AUTH_MODE
          value: ldap_auth
        - name: LDAP_URL
          value: ldap://193.169.0.132:389
        - name: LDAP_BASE_DN
          value: cn=%s,ou=Users,dc=openstack,dc=org
        - name: LOG_LEVEL
          value: debug
        - name: MYSQL_PWD
          value: root123
        image: registry.dataos.io/liuliu/harbor-ui:1.0.1
        imagePullPolicy: Always
        name: ui
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      nodeSelector:
        node: node-3.11
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  replicas: 0
