apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  generation: 1
  labels:
    name: proxy2
  name: proxy2
spec:
  replicas: 1
  selector:
    name: proxy2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cluster
        name: proxy2
    spec:
      containers:
      - image: registry.dataos.io/liuliu/harbor_proxy:latest
        imagePullPolicy: Always
        name: proxy2
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /etc/nginx
          name: nginx-config2
      dnsPolicy: ClusterFirst
      nodeSelector:
        node: node-3.11
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nginx-config2
        secret:
          secretName: nginx-config2
status:
  replicas: 0
